### ISSUE TITLE
error running fastgeoapi  in local

### ISSUE THREAD

**Issue by krishnaglodha** [geobeyond/fastgeoapi#100]
I'm trying to run fastgeoapi in local ( Machine - Intel Macbook ) 

## Steps I have taken
1. I have created poetry shell and installed everything
2. started docker-compose file

But getting following errors
<img width="798" alt="Screenshot_2023-07-20_at_5 48 24_PM" src="https://github.com/geobeyond/fastgeoapi/assets/47075664/025957ea-03b1-4354-b8b0-70b7badac8f8">
<img width="1440" alt="Screenshot_2023-07-20_at_5 51 36_PM" src="https://github.com/geobeyond/fastgeoapi/assets/47075664/55558e2b-31c7-4ff9-9a24-3791d70b89c1">

I have changed all ports to `5050` 
I have changed in  `pygeoapi-openapi.yml` and `pygeoapi-config.yml` as well. 

I'm executing following command 
`uvicorn app.main:app --port 5050 --loop asyncio --reload`

**Comment by francbartoli** [comment]
@krishnaglodha can you clarify where did you change the port?

**Comment by krishnaglodha** [comment]
config.yml
<img width="575" alt="Screenshot 2023-07-20 at 10 40 27 PM" src="https://github.com/geobeyond/fastgeoapi/assets/47075664/c33a8c8e-68c7-45aa-a6b9-a123386793fb">

openapi.yml
<img width="747" alt="Screenshot 2023-07-20 at 10 40 49 PM" src="https://github.com/geobeyond/fastgeoapi/assets/47075664/52bcf2f7-8f56-4861-93ab-6b8c511659f1">

**Comment by francbartoli** [comment]
@krishnaglodha is it solved now?
