### ISSUE TITLE
docker composition not working on M1 arm64 architecture

### ISSUE THREAD

**Issue by francbartoli** [geobeyond/fastgeoapi#101]
Error is coming up with the following:

```shell
❯ docker compose up -d
image with reference postgres:14.3 was found but does not match the specified platform: wanted linux/amd64, actual: linux/arm64/v8
```

**Comment by francbartoli** [comment]
Apparently `RedHat` is building only `linux/arm64`arch so we need to build our own images. We can follow official instructions [https://www.keycloak.org/server/containers](https://www.keycloak.org/server/containers )on running Keycloak in a container

**Comment by francbartoli** [comment]
@krishnaglodha can you check with that variable if then it works?

**Comment by krishnaglodha** [comment]
Thanks, will check and revert

**Comment by krishnaglodha** [comment]
yes! It works

**Comment by krishnaglodha** [comment]
I believe we should remove `platform` from docker-compose all together. thoughts ? @francbartoli

**Comment by francbartoli** [comment]
I don't see it in [develop](https://github.com/geobeyond/fastgeoapi/blob/develop/scripts/iam/docker-compose.yml)
